"""Generated-span CE and small separate GAD discriminator; CPU-testable."""
from dataclasses import dataclass
from bisect import bisect_right
import re

import torch
from torch import nn
from torch.nn import functional as F

SMARTAD_WEIGHTS = {"reason": 1., "action": 1.5, "final": 2., "observation": 0.}
MARKERS = re.compile(
    r"\[/?(?:REASON|ACT|FINAL|OBSERVATION|OBS)\]|"
    r"(?im:^[ \t]*(?:THOUGHT|REASON|ACTION|ACT|FINAL(?: ANSWER)?|ANSWER|OBSERVATION|OBS):)|"
    r"<think>|</think>|<\|channel>thought\n|<channel\|>|"
    r"<\|tool_call>|<\|tool_response>|<\|turn>(?:user|tool)[^\n]*\n")
HOTPOTQA_MARKERS = re.compile(
    r"(?im:^[ \t]*(?:Action[ \t]*\d*[ \t]*:[ \t]*)?"
    r"(?P<verb>search|lookup|finish)\[[^\n]*\][ \t]*(?=$|<turn\|>|<eos>))|"
    r"(?im:^[ \t]*(?:Thought|Action|Observation)[ \t]*\d*[ \t]*:)|" + MARKERS.pattern)


def hotpotqa_prefill_kind(prompt):
    # The native Gemma generation suffix follows the final user turn. Inspect
    # that turn's trailing ReAct prefill, not earlier six-shot examples or the
    # model's empty native thought channel. Retries end in Action n:.
    content = prompt.rsplit("<turn|>", 1)[0]
    prefill = re.search(r"(?im:^[ \t]*(Thought|Action)[ \t]*\d*[ \t]*:)[ \t]*\Z", content.rstrip())
    return "action" if prefill and prefill[1].lower() == "action" else "reason"


@dataclass(frozen=True)
class Span:
    start: int
    end: int
    kind: str


def segment_spans(text, *, benchmark="bfcl", final_step=False, prompt=""):
    """Disjoint exhaustive spans; observations never receive a training label.

    Plain ALF commands are actions (the terminal command is a final decision).
    ALF authored text preceding the first action marker is reasoning.
    BFCL prose is final; native tool calls are actions. Native format tokens
    are generated tokens too, including the empty thought block and EOS.
    HotpotQA inherits its numbered prefill; only finish is a final decision.
    """
    default = "final" if benchmark == "bfcl" or final_step else "action"
    if benchmark == "hotpotqa":
        default = hotpotqa_prefill_kind(prompt)
    kind, cursor, spans = default, 0, []
    first_alfworld_action = None
    markers = HOTPOTQA_MARKERS if benchmark == "hotpotqa" else MARKERS
    for match in markers.finditer(text):
        if cursor < match.start():
            spans.append(Span(cursor, match.start(), kind))
        marker = match.group().strip().upper()
        if benchmark == "hotpotqa" and match["verb"]:
            # A bare tool-looking line inside Wikipedia output is still an
            # observation. An explicit Action label resumes authored text.
            if kind != "observation" or marker.startswith("ACTION"):
                kind = "final" if match["verb"].lower() == "finish" else "action"
            cursor = match.start()
            continue
        if marker == "<|TOOL_RESPONSE>":
            # Handoff is generated by the model, not an observed tool result.
            spans.append(Span(match.start(), match.end(), "action"))
            kind, cursor = "observation", match.end()
            continue
        if marker in {"</THINK>", "<CHANNEL|>", "[/REASON]", "[/ACT]", "[/FINAL]", "[/OBS]", "[/OBSERVATION]"}:
            # Closing token belongs to the span it terminates.
            spans.append(Span(match.start(), match.end(), kind))
            kind, cursor = default, match.end()
            continue
        if "OBS" in marker or "TOOL_RESPONSE" in marker or marker.startswith("<|TURN>"):
            kind = "observation"
        elif any(word in marker for word in ("THOUGHT", "THINK", "REASON")):
            kind = "reason"
        elif "ACT" in marker or "TOOL_CALL" in marker:
            if benchmark == "alfworld" and first_alfworld_action is None:
                first_alfworld_action = match.start()
            kind = "final" if benchmark == "alfworld" and final_step else "action"
        else:
            kind = "final"
        cursor = match.start()
    if cursor < len(text):
        spans.append(Span(cursor, len(text), kind))
    if first_alfworld_action is not None:
        # ReAct does not require THOUGHT labels. Keep observed prefixes masked
        # and preserve the existing command-only and terminal-action behavior.
        spans = [Span(s.start, s.end, "reason")
                 if s.end <= first_alfworld_action and s.kind != "observation" else s
                 for s in spans]
    return spans


def token_kinds(tokenizer, text, *, benchmark, final_step=False, prompt=""):
    """Classify exact target IDs using fast-tokenizer offsets, never re-tokenize spans."""
    encoded = tokenizer(text, add_special_tokens=False, return_offsets_mapping=True)
    spans = segment_spans(text, benchmark=benchmark, final_step=final_step, prompt=prompt)
    ends = [s.end for s in spans]
    kinds = []
    for start, end in encoded["offset_mapping"]:
        # Disjoint spans are ordered. Avoid scanning every trajectory span for
        # every token (quadratic on long alternating action/observation text).
        index = bisect_right(ends, start)
        overlap = []
        while index < len(spans) and spans[index].start < end:
            overlap.append(spans[index])
            index += 1
        if any(s.kind == "observation" for s in overlap):
            kind = "observation"  # mask any boundary token touching environment text
        elif overlap:
            kind = max(overlap, key=lambda s: min(end, s.end)-max(start, s.start)).kind
        else:
            raise ValueError("tokenizer must expose offsets for authored target tokens")
        kinds.append(kind)
    return tuple(encoded["input_ids"]), kinds


def span_ce(token_logprobs, kinds, method):
    values = token_logprobs.reshape(-1)
    if values.numel() != len(kinds) or not len(kinds):
        raise ValueError("token/span alignment mismatch")
    mask = values.new_tensor([k != "observation" for k in kinds], dtype=torch.bool)
    if not mask.any():
        raise ValueError("row has no generated supervision")
    if method == "sad":
        # [REASON] and [ACT] are span labels, not added deployment pseudo-tags.
        # Final decisions belong to ACT in this two-head text-only adaptation.
        groups = []
        for group in ({"reason"}, {"action", "final"}):
            selected = values.new_tensor([k in group for k in kinds], dtype=torch.bool)
            if selected.any():
                groups.append(-values[selected].mean())
        return torch.stack(groups).mean()
    weights = values.new_tensor([SMARTAD_WEIGHTS[k] if method == "smartad"
                                else float(k != "observation") for k in kinds])
    # Divide by generated length, preserving the declared absolute segment weights.
    return -(values * weights).sum() / mask.sum()


class SmallDiscriminator(nn.Module):
    """Separate byte embedding/GRU pair scorer; no student-gradient connection.

    Reads the complete prompt and response. Prompt/response GRU summaries and
    their product condition the score on the same prompt for both contestants.
    """
    def __init__(self, width=32, hidden=64):
        super().__init__()
        self.embedding = nn.Embedding(257, width)
        self.encoder = nn.GRU(width, hidden, batch_first=True)
        self.head = nn.Sequential(nn.Linear(3*hidden, hidden), nn.Tanh(), nn.Linear(hidden, 1))

    def encode(self, text):
        device = self.embedding.weight.device
        ids = torch.tensor([list(text.encode("utf-8")) or [256]], device=device)
        _, hidden = self.encoder(self.embedding(ids))
        return hidden[-1, 0]

    def forward(self, prompts, responses):
        if len(prompts) != len(responses) or not prompts:
            raise ValueError("paired nonempty discriminator input required")
        scores = []
        for prompt, response in zip(prompts, responses):
            p, r = self.encode(prompt), self.encode(response)
            scores.append(self.head(torch.cat((p, r, p*r))).squeeze(-1))
        return torch.stack(scores)


def discriminator_loss(teacher_scores, student_scores):
    """GAD Bradley–Terry preference loss at identical prompts."""
    if teacher_scores.shape != student_scores.shape or not teacher_scores.numel():
        raise ValueError("paired discriminator scores required")
    return -F.logsigmoid(teacher_scores-student_scores).mean()


def group_advantages(rewards, epsilon=1e-6):
    if rewards.ndim != 1 or rewards.numel() < 2 or not torch.isfinite(rewards).all():
        raise ValueError("finite reward group of size >= 2 required")
    rewards = rewards.detach()
    return (rewards-rewards.mean()) / rewards.std(unbiased=False).clamp_min(epsilon)


def grpo_loss(logprobs, old_logprobs, advantage, clip=0.2):
    """One group-relative, length-normalized policy update; rewards stop-gradient."""
    if logprobs.shape != old_logprobs.shape or not logprobs.numel():
        raise ValueError("aligned generated token log probabilities required")
    ratio = (logprobs-old_logprobs.detach()).exp()
    advantage = torch.as_tensor(advantage, device=ratio.device).detach()
    return -torch.minimum(ratio*advantage, ratio.clamp(1-clip, 1+clip)*advantage).mean()
